# Generated by Django 6.0 on 2025-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_jobposting_like_share_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='category',
            field=models.CharField(choices=[('RAILWAY', 'Railway'), ('BANKING', 'Banking'), ('SSC', 'SSC'), ('UPSC', 'UPSC'), ('STATE_GOVT', 'State Govt'), ('TEACHING', 'Teaching'), ('OTHER', 'Other')], default='RAILWAY', max_length=20),
        ),
    ]
