# Generated by Django 6.0 on 2025-12-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
